language: node_js
node_js: '6'
cache: npm
os: windows

branches:
  only:
  - fix-electron-locator
  - master
  - /^v\d+\.\d+\.\d+/

before_install:
- |
    choco install vcbuildtools
    export NPM_CONFIG_PREFIX=c:\\custom_npm PATH="/c/custom_npm:$PATH" VCTargetsPath="C:\\Program Files (x86)\\MSBuild\\Microsoft.cpp\\v4.0\\v140"
    npm install -g npm@6
    npm config set msvs_version 2015 --global

before_script:
  # remove "electron" folder for electron-locater tests
  - |
      if [[ "$TRAVIS_REPO_SLUG" = "electron/electron-rebuild" ]]; then
        cd ../../ && mv ./$TRAVIS_REPO_SLUG ./electron-rebuild && rm -rf ./electron && cd ./electron-rebuild/
      fi
