build: off

environment:
  matrix:
  - nodejs_version: "6"

skip_tags: true

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@6
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
